import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'package:omnistudin_flutter/Logic/Frontend_To_Backend_Connection.dart';

class FindFriendsPage extends StatefulWidget {
//  final int tabIndex;
//  const FindFriendsPage({super.key, required this.tabIndex});

  @override
  _FindFriendsPageState createState() => _FindFriendsPageState();
}

class _FindFriendsPageState extends State<FindFriendsPage> {
  List<dynamic> friendsList = []; // List to hold friends data
  final _formKey = GlobalKey<FormState>();
  final _emailController = TextEditingController();

  @override
  void initState() {
    super.initState();
    fetchInterestingFriends();
  }

  Future<void> fetchInterestingFriends() async {
    FrontendToBackendConnection.getData("find_friends/").then((data) {
      if (data is http.Response) {
        if (data.statusCode == 200) {
          setState(() {
            friendsList = json.decode(data.body);
            print(friendsList);
          });
        } else {
          print('Failed to load friends');
        }
      } else if (data is List<dynamic>) {
        setState(() {
          friendsList = data;
          print(friendsList);
        });
      }
    });
  }

  Future<void> addFriend(String email) async {
    print(email);
    await FrontendToBackendConnection.postData(
        "send_friend_request/", {"friend_email": email}).then((response) {
      var responseData = response;
      showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Friend Request'),
            content: response["success"] != null
                ? Text(responseData["success"])
                : response["error"] != null
                    ? Text(responseData["error"])
                    : Text('An error occurred'),
            actions: <Widget>[
              TextButton(
                child: Text('OK'),
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
            ],
          );
        },
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: Icon(Icons.arrow_back),
          onPressed: () {
            print("returning to friends page");
            Navigator.pop(context, 'fetchFriends');
          },
        ),
        centerTitle: true,
        title: Container(
          width: 280,
          height: 400,
          child: Image.asset('assets/images/logo_name.png'),
        ),
        actions: [
          IconButton(
            icon: Icon(Icons.help_outline),
            onPressed: () {
              showDialog(
                context: context,
                builder: (BuildContext context) {
                  return AlertDialog(
                    title: Text('Friend Suggestions'),
                    content: Text(
                        'The friends suggestions here are generated by a complex algorithm based on your interests, activities, and connections.'),
                    actions: <Widget>[
                      TextButton(
                        child: Text('OK'),
                        onPressed: () {
                          Navigator.of(context).pop();
                        },
                      ),
                    ],
                  );
                },
              );
            },
          ),
        ],
      ),
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: ListView.builder(
                itemCount: friendsList.length,
                itemBuilder: (context, index) {
                  return Card(
                    child: ListTile(
                      leading: friendsList[index]['profile_picture'] != null
                          ? ClipOval(
                              child: Image.memory(base64Decode(
                                  friendsList[index]['profile_picture'])),
                            )
                          : Icon(Icons
                              .person), // replace with actual image if available
                      title: Text(friendsList[index]['forename'] ??
                          'No name'), // use 'forename' field
                      subtitle: Text(friendsList[index]['bio'] ??
                          'No bio'), // use 'bio' field
                      trailing: PopupMenuButton<String>(
                        onSelected: (value) {
                          if (value == 'add_friend') {
                            addFriend(friendsList[index]['email']);
                          }
                        },
                        itemBuilder: (BuildContext context) =>
                            <PopupMenuEntry<String>>[
                          const PopupMenuItem<String>(
                            value: 'add_friend',
                            child: Text('Add Friend'),
                          ),
                        ],
                      ),
                      onTap: () {
                        showDialog(
                          context: context,
                          builder: (BuildContext context) {
                            return AlertDialog(
                              title: Center(
                                child: Text(
                                  '${friendsList[index]['forename']} ${friendsList[index]['surname'] ?? ''}',
                                  style: TextStyle(fontWeight: FontWeight.bold),
                                ),
                              ),
                              content: SingleChildScrollView(
                                child: ListBody(
                                  children: <Widget>[
                                    if (friendsList[index]['profile_picture'] !=
                                        null)
                                      Padding(
                                        padding:
                                            const EdgeInsets.only(bottom: 8.0),
                                        child: Center(
                                          child: ClipOval(
                                            child: Image.memory(base64Decode(
                                                friendsList[index]
                                                    ['profile_picture'])),
                                          ),
                                        ),
                                      ),
                                    if (friendsList[index]['bio'] != null)
                                      RichText(
                                        text: TextSpan(
                                          text: 'Bio:\n',
                                          style: DefaultTextStyle.of(context)
                                              .style
                                              .copyWith(
                                                  fontWeight: FontWeight.bold),
                                          children: <TextSpan>[
                                            TextSpan(
                                                text:
                                                    '${friendsList[index]['bio']}',
                                                style: TextStyle(
                                                    fontWeight:
                                                        FontWeight.normal)),
                                          ],
                                        ),
                                      ),
                                    if (friendsList[index]['uni_name'] != null)
                                      RichText(
                                        text: TextSpan(
                                          text: 'University:\n',
                                          style: DefaultTextStyle.of(context)
                                              .style
                                              .copyWith(
                                                  fontWeight: FontWeight.bold),
                                          children: <TextSpan>[
                                            TextSpan(
                                                text:
                                                    '${friendsList[index]['uni_name']}',
                                                style: TextStyle(
                                                    fontWeight:
                                                        FontWeight.normal)),
                                          ],
                                        ),
                                      ),
                                    if (friendsList[index]['degree'] != null)
                                      RichText(
                                        text: TextSpan(
                                          text: 'Degree:\n',
                                          style: DefaultTextStyle.of(context)
                                              .style
                                              .copyWith(
                                                  fontWeight: FontWeight.bold),
                                          children: <TextSpan>[
                                            TextSpan(
                                                text:
                                                    '${friendsList[index]['degree']}',
                                                style: TextStyle(
                                                    fontWeight:
                                                        FontWeight.normal)),
                                          ],
                                        ),
                                      ),
                                    if (friendsList[index]['semester'] != null)
                                      RichText(
                                        text: TextSpan(
                                          text: 'Semester:\n',
                                          style: DefaultTextStyle.of(context)
                                              .style
                                              .copyWith(
                                                  fontWeight: FontWeight.bold),
                                          children: <TextSpan>[
                                            TextSpan(
                                                text:
                                                    '${friendsList[index]['semester']}',
                                                style: TextStyle(
                                                    fontWeight:
                                                        FontWeight.normal)),
                                          ],
                                        ),
                                      ),
                                  ],
                                ),
                              ),
                              actions: <Widget>[
                                TextButton(
                                  child: Text('Close'),
                                  onPressed: () {
                                    Navigator.of(context).pop();
                                  },
                                ),
                              ],
                            );
                          },
                        );
                      },
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
